extra_challenges = ["Integrar Inteligencia Artificial",
                    "Modo multijugador en línea",
                    "Mecánica de juego original",
                    "Sistema de física avanzado",
                    "Sistema de logros y recompensas",
                    "Animaciones complejas",
                    "Realidad aumentada",
                    "Realidad virtual",
                    "Dialogos y narrativa compleja",
                    "Editor de niveles",
                    "Modos de dificultad",
                    "Soporte para diferentes idiomas",
                    "Personalización de personajes",
                    "Logros por progreso",
                    "Análisis de datos para estudiar el comportamiento del jugador",
                    "Geolocalización",
                    "Soporte multiplataforma",
                    "Personalización de controles adaptables por el usuario",
                    "Sistema de progresión de personaje con habilidades y atributos",
                    "Reconocimiento de voz para controlar el juego",
                    "Sistema de diágolo y elecciones que modifican el desarrollo de la historia del juego",
                    "Ciclo de día y noche",
                    "Minijuegos dentro del juego principal",
                    "Generación procedural de niveles o escenarios",
                    "Sistema de mascotas/compañeros que ayuden al jugador",
                    "Mecánica de juego basada en la teoría del caos"]