frameworks_languages = ["Unity - C#",
                        "libGDX - Java",
                        "PyGame - Python",
                        "Phaser - JavaScript",
                        "Unreal Engine - C++",
                        "Gosu - Ruby",
                        "LÖVE - Lua",
                        "SpriteKit - Swift",
                        "Babylon.js - TypeScript",
                        "OpenFL - Haxe",
                        "Amethyst - Rust",
                        "Ebiten - Go",
                        "Korge - Kotlin",
                        "Flame - Dart",
                        "Scalajs - Scala",
                        "Defold - Lua",
                        "Elm Game - Elm",
                        "Quil - Clojure",
                        "Godot - PHP",
                        "GB Studio - Assembly",
                        "Rust-Graphics - Rust",
                        "Three.js - JavaScript",
                        "Corona SDK - Lua",
                        "XNA/Monogame - C#",
                        "Ren'Py - Python",
                        "A-Frame - TypeScript",
                        "Heaps - Haxe",
                        "SFML - C++",
                        "Metal - Swift",
                        "Pixel - Go",
                        "LibKTX - Kotlin",
                        "Love2D - Lua",
                        "Phaser.io - PHP",
                        "Panda3D - Python"]