game_types = ["Arcade clásico",
              "RPG",
              "RPG por turnos",
              "Aventura gráfica",
              "Estrategia",
              "Cartas",
              "Plataforma",
              "Acción",
              "Simulación",
              "Deportes",
              "Puzzle",
              "Lógica",
              "Música",
              "Carreras",
              "Shooter en primera persona",
              "Shooter en tercera persona",
              "Construcción",
              "Supervivencia",
              "Sigilo",
              "Mundo abierto",
              "Estrategia en tiempo real",
              "Estrategia por turnos",
              "Terror",
              "Battle Royale",
              "Estrategia con cartas",
              "Cartas coleccionables",
              "Gestión de tiempo",
              "Aventura en primera persona"]