game_themes = ["Viaje en el tiempo",
               "Zombies",
               "Superhéroes",
               "Espacio",
               "Mitología griega",
               "Fantasía medieval",
               "Detectives",
               "Deportes",
               "Historial mundial",
               "Robots",
               "Inteligencia artificial",
               "Retro",
               "Arte",
               "Enigmas",
               "Guerra",
               "Genética",
               "Supervivencia en la naturaleza",
               "Educación",
               "Magia",
               "Música",
               "Piratas",
               "Automóviles",
               "Tesoros",
               "Parque de atrcciones",
               "Supersticiones",
               "Arqueología",
               "Ciudad del futuro",
               "Artes marciales",
               "Espionaje",
               "Ciencia ficción",
               "Cocina",
               "Animales",
               "Barcos",
               "Mitología nórdica",
               "Conspiración",
               "Expedición a la antártida",
               "Dragones",
               "Leyendas urbanas",
               "Mundo submarino",
               "Ciudad inteligente",
               "Egiptología"]